package terraform

import (
	"bufio"
	"fmt"
	"os"
	"regexp"
	"sort"
	"strings"

	"github.com/DataDog/pathfinding-labs/internal/config"
)

// TFVars manages terraform.tfvars file
type TFVars struct {
	path string
}

// NewTFVars creates a new TFVars manager
func NewTFVars(path string) *TFVars {
	return &TFVars{path: path}
}

// Exists checks if the tfvars file exists
func (t *TFVars) Exists() bool {
	_, err := os.Stat(t.path)
	return err == nil
}

// GetEnabledScenarios returns a map of scenario variable names to their enabled state
func (t *TFVars) GetEnabledScenarios() (map[string]bool, error) {
	enabled := make(map[string]bool)

	if !t.Exists() {
		return enabled, nil
	}

	file, err := os.Open(t.path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	// Match lines like: enable_scenario_name = true
	enablePattern := regexp.MustCompile(`^\s*(enable_\S+)\s*=\s*(true|false)\s*$`)

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()
		matches := enablePattern.FindStringSubmatch(line)
		if len(matches) == 3 {
			varName := matches[1]
			value := matches[2] == "true"
			enabled[varName] = value
		}
	}

	return enabled, scanner.Err()
}

// SetScenarioEnabled enables or disables a scenario
func (t *TFVars) SetScenarioEnabled(variableName string, enabled bool) error {
	// Read existing content
	content, err := t.readContent()
	if err != nil && !os.IsNotExist(err) {
		return err
	}

	// Check if variable already exists
	varPattern := regexp.MustCompile(fmt.Sprintf(`(?m)^\s*%s\s*=\s*(true|false)\s*$`, regexp.QuoteMeta(variableName)))

	if varPattern.MatchString(content) {
		// Update existing variable
		replacement := fmt.Sprintf("%s = %t", variableName, enabled)
		content = varPattern.ReplaceAllString(content, replacement)
	} else {
		// Add new variable
		if content != "" && !strings.HasSuffix(content, "\n") {
			content += "\n"
		}
		content += fmt.Sprintf("%s = %t\n", variableName, enabled)
	}

	return t.writeContent(content)
}

// SetMultipleScenariosEnabled enables or disables multiple scenarios
func (t *TFVars) SetMultipleScenariosEnabled(variables []string, enabled bool) error {
	// Read existing content
	content, err := t.readContent()
	if err != nil && !os.IsNotExist(err) {
		return err
	}

	for _, variableName := range variables {
		varPattern := regexp.MustCompile(fmt.Sprintf(`(?m)^\s*%s\s*=\s*(true|false)\s*$`, regexp.QuoteMeta(variableName)))

		if varPattern.MatchString(content) {
			replacement := fmt.Sprintf("%s = %t", variableName, enabled)
			content = varPattern.ReplaceAllString(content, replacement)
		} else {
			if content != "" && !strings.HasSuffix(content, "\n") {
				content += "\n"
			}
			content += fmt.Sprintf("%s = %t\n", variableName, enabled)
		}
	}

	return t.writeContent(content)
}

// InitFromConfig creates a new tfvars file from the given config
func (t *TFVars) InitFromConfig(cfg *config.Config) error {
	var lines []string

	// Add header
	lines = append(lines, "# Pathfinding Labs Configuration")
	lines = append(lines, "# Generated by plabs init")
	lines = append(lines, "")

	// Add account configuration
	// NOTE: Account IDs are automatically derived from AWS profiles via aws_caller_identity
	lines = append(lines, "# AWS Account Configuration")
	lines = append(lines, "# Account IDs are auto-derived from profiles - no need to specify them!")
	lines = append(lines, "enable_prod_environment  = true")
	lines = append(lines, fmt.Sprintf("prod_account_aws_profile = %q", cfg.ProdProfile))
	if cfg.ProdRegion != "" {
		lines = append(lines, fmt.Sprintf("aws_region               = %q", cfg.ProdRegion))
	}
	lines = append(lines, "")

	// Dev environment (optional)
	if cfg.DevProfile != "" {
		lines = append(lines, "# Dev Environment (for cross-account scenarios)")
		lines = append(lines, "enable_dev_environment  = true")
		lines = append(lines, fmt.Sprintf("dev_account_aws_profile = %q", cfg.DevProfile))
		lines = append(lines, "")
	}

	// Ops environment (optional)
	if cfg.OpsProfile != "" {
		lines = append(lines, "# Ops Environment (for cross-account scenarios)")
		lines = append(lines, "enable_ops_environment         = true")
		lines = append(lines, fmt.Sprintf("operations_account_aws_profile = %q", cfg.OpsProfile))
		lines = append(lines, "")
	}

	// Add scenario section
	lines = append(lines, "# Enabled Scenarios")
	lines = append(lines, "# Use 'plabs enable <scenario-id>' to enable scenarios")
	lines = append(lines, "")

	content := strings.Join(lines, "\n")
	return t.writeContent(content)
}

// GetAccountConfig reads the account configuration from tfvars
func (t *TFVars) GetAccountConfig() (*config.Config, error) {
	cfg := &config.Config{}

	if !t.Exists() {
		return cfg, nil
	}

	content, err := t.readContent()
	if err != nil {
		return nil, err
	}

	// Parse account IDs and profiles
	patterns := map[string]*string{
		`prod_account_id\s*=\s*"([^"]+)"`:                &cfg.ProdAccountID,
		`prod_account_aws_profile\s*=\s*"([^"]+)"`:       &cfg.ProdProfile,
		`dev_account_id\s*=\s*"([^"]+)"`:                 &cfg.DevAccountID,
		`dev_account_aws_profile\s*=\s*"([^"]+)"`:        &cfg.DevProfile,
		`operations_account_id\s*=\s*"([^"]+)"`:          &cfg.OpsAccountID,
		`operations_account_aws_profile\s*=\s*"([^"]+)"`: &cfg.OpsProfile,
	}

	for pattern, target := range patterns {
		re := regexp.MustCompile(pattern)
		matches := re.FindStringSubmatch(content)
		if len(matches) == 2 {
			*target = matches[1]
		}
	}

	return cfg, nil
}

// ListEnabledScenarios returns a sorted list of enabled scenario variable names
func (t *TFVars) ListEnabledScenarios() ([]string, error) {
	enabled, err := t.GetEnabledScenarios()
	if err != nil {
		return nil, err
	}

	var result []string
	for name, isEnabled := range enabled {
		if isEnabled {
			result = append(result, name)
		}
	}

	sort.Strings(result)
	return result, nil
}

// GetEnabledEnvironments returns the enabled state of each environment
func (t *TFVars) GetEnabledEnvironments() (prod, dev, ops bool, err error) {
	if !t.Exists() {
		return true, false, false, nil // Default: only prod enabled
	}

	content, err := t.readContent()
	if err != nil {
		return false, false, false, err
	}

	// Parse environment enabled flags
	prodPattern := regexp.MustCompile(`(?m)^\s*enable_prod_environment\s*=\s*(true|false)`)
	devPattern := regexp.MustCompile(`(?m)^\s*enable_dev_environment\s*=\s*(true|false)`)
	opsPattern := regexp.MustCompile(`(?m)^\s*enable_ops_environment\s*=\s*(true|false)`)

	// Default prod to true if not specified
	prod = true
	if matches := prodPattern.FindStringSubmatch(content); len(matches) == 2 {
		prod = matches[1] == "true"
	}

	if matches := devPattern.FindStringSubmatch(content); len(matches) == 2 {
		dev = matches[1] == "true"
	}

	if matches := opsPattern.FindStringSubmatch(content); len(matches) == 2 {
		ops = matches[1] == "true"
	}

	return prod, dev, ops, nil
}

// SetEnvironmentEnabled enables or disables an environment
func (t *TFVars) SetEnvironmentEnabled(env string, enabled bool) error {
	varName := ""
	switch env {
	case "prod":
		varName = "enable_prod_environment"
	case "dev":
		varName = "enable_dev_environment"
	case "ops":
		varName = "enable_ops_environment"
	default:
		return fmt.Errorf("unknown environment: %s", env)
	}

	// Read existing content
	content, err := t.readContent()
	if err != nil && !os.IsNotExist(err) {
		return err
	}

	// Check if variable already exists
	varPattern := regexp.MustCompile(fmt.Sprintf(`(?m)^\s*%s\s*=\s*(true|false)\s*$`, regexp.QuoteMeta(varName)))

	if varPattern.MatchString(content) {
		// Update existing variable
		replacement := fmt.Sprintf("%s = %t", varName, enabled)
		content = varPattern.ReplaceAllString(content, replacement)
	} else {
		// Add new variable
		if content != "" && !strings.HasSuffix(content, "\n") {
			content += "\n"
		}
		content += fmt.Sprintf("%s = %t\n", varName, enabled)
	}

	return t.writeContent(content)
}

// SetProfile sets the AWS profile for an environment
func (t *TFVars) SetProfile(env string, profile string) error {
	varName := ""
	switch env {
	case "prod":
		varName = "prod_account_aws_profile"
	case "dev":
		varName = "dev_account_aws_profile"
	case "ops":
		varName = "operations_account_aws_profile"
	default:
		return fmt.Errorf("unknown environment: %s", env)
	}

	// Read existing content
	content, err := t.readContent()
	if err != nil && !os.IsNotExist(err) {
		return err
	}

	// Check if variable already exists
	varPattern := regexp.MustCompile(fmt.Sprintf(`(?m)^\s*%s\s*=\s*"[^"]*"\s*$`, regexp.QuoteMeta(varName)))

	if varPattern.MatchString(content) {
		// Update existing variable
		replacement := fmt.Sprintf(`%s = "%s"`, varName, profile)
		content = varPattern.ReplaceAllString(content, replacement)
	} else {
		// Add new variable
		if content != "" && !strings.HasSuffix(content, "\n") {
			content += "\n"
		}
		content += fmt.Sprintf(`%s = "%s"`+"\n", varName, profile)
	}

	return t.writeContent(content)
}

// readContent reads the entire tfvars file
func (t *TFVars) readContent() (string, error) {
	data, err := os.ReadFile(t.path)
	if err != nil {
		return "", err
	}
	return string(data), nil
}

// writeContent writes content to the tfvars file
func (t *TFVars) writeContent(content string) error {
	return os.WriteFile(t.path, []byte(content), 0644)
}
