# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plabs < Formula
  desc "CLI for managing Pathfinding Labs AWS attack scenarios"
  homepage "https://github.com/DataDog/pathfinding-labs"
  version "1.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DataDog/pathfinding-labs/releases/download/v1.0.1/plabs_1.0.1_darwin_amd64.tar.gz"
      sha256 "fc5a4fcc711ef4d91a051e0d920052cf1ce5eb5fe17067f6ef5220fdcfe97585"

      define_method(:install) do
        bin.install "plabs"
        generate_completions_from_executable(bin/"plabs", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DataDog/pathfinding-labs/releases/download/v1.0.1/plabs_1.0.1_darwin_arm64.tar.gz"
      sha256 "30d6765a1c8e3f7a2916a38e919ffc83cba0d30d4daab3288ff10434d22fdf7a"

      define_method(:install) do
        bin.install "plabs"
        generate_completions_from_executable(bin/"plabs", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DataDog/pathfinding-labs/releases/download/v1.0.1/plabs_1.0.1_linux_amd64.tar.gz"
      sha256 "9a31197d13a26b4b214290e36c645ded22ff922baaf333f3f703bd2fee5d07fb"
      define_method(:install) do
        bin.install "plabs"
        generate_completions_from_executable(bin/"plabs", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DataDog/pathfinding-labs/releases/download/v1.0.1/plabs_1.0.1_linux_arm64.tar.gz"
      sha256 "66500d37bb0a8fea16bf618e9b8ee60209343b489604cdad57b7c4b15296b5bb"
      define_method(:install) do
        bin.install "plabs"
        generate_completions_from_executable(bin/"plabs", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/plabs version")
  end
end
