# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Plabs < Formula
  desc "CLI for managing Pathfinding Labs AWS attack scenarios"
  homepage "https://github.com/DataDog/pathfinding-labs"
  version "0.0.13"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/DataDog/pathfinding-labs/releases/download/v0.0.13/plabs_0.0.13_darwin_amd64.tar.gz"
      sha256 "ccf443b503a1c77c30cb49f5820a7f6e1570733096ba2437370f8ed46390f1be"

      define_method(:install) do
        bin.install "plabs"
        generate_completions_from_executable(bin/"plabs", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/DataDog/pathfinding-labs/releases/download/v0.0.13/plabs_0.0.13_darwin_arm64.tar.gz"
      sha256 "2b3321c93590befd24535aeb997aa008a53fea139ca6a33d4c7bf25cb5c26651"

      define_method(:install) do
        bin.install "plabs"
        generate_completions_from_executable(bin/"plabs", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/DataDog/pathfinding-labs/releases/download/v0.0.13/plabs_0.0.13_linux_amd64.tar.gz"
      sha256 "020330fc599bf1308b5b5310e36bbced045d4316ec4691f167c70de89f66a7ab"
      define_method(:install) do
        bin.install "plabs"
        generate_completions_from_executable(bin/"plabs", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/DataDog/pathfinding-labs/releases/download/v0.0.13/plabs_0.0.13_linux_arm64.tar.gz"
      sha256 "3e331e2100a171d26121899cf1e8df9fdd5d1ef5a6edd7f536283731a6f9eb6d"
      define_method(:install) do
        bin.install "plabs"
        generate_completions_from_executable(bin/"plabs", "completion")
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/plabs version")
  end
end
